# Generated by Django 3.0.3 on 2020-03-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller')], default='B', max_length=2)),
                ('content', models.CharField(default='system', max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
