# Generated by Django 3.0.3 on 2020-02-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_image.jpg', storage='product_image', upload_to=''),
        ),
    ]
