# Generated by Django 3.0.3 on 2020-03-07 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200302_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.CharField(default='system', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
