# Generated by Django 3.0.3 on 2020-03-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_auto_20200307_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='name',
        ),
    ]
