# Generated by Django 3.0.3 on 2020-03-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200308_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.TextField(default=None),
        ),
    ]
