# Generated by Django 3.0.3 on 2020-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(default='default_image.jpg', upload_to='product_images/')),
            ],
        ),
    ]
