# Generated by Django 3.0.3 on 2020-03-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_remove_teammember_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='picture',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images/'),
        ),
    ]
